//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// Details of an invoice cancel notification.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class CancelNotification : PayPalSerializableObject
    {
        /// <summary>
        /// Subject of the notification.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "subject")]
        public string subject { get; set; }

        /// <summary>
        /// Note to the payer.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "note")]
        public string note { get; set; }

        /// <summary>
        /// A flag indicating whether a copy of the email has to be sent to the merchant.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "send_to_merchant")]
        public bool? send_to_merchant { get; set; }

        /// <summary>
        /// A flag indicating whether a copy of the email has to be sent to the payer.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "send_to_payer")]
        public bool? send_to_payer { get; set; }
    }
}
