//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// A REST API extended bank account resource.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class ExtendedBankAccount : BankAccount
    {
        /// <summary>
        /// Identifier of the direct debit mandate to validate. Currently supported only for EU bank accounts(SEPA).
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "mandate_reference_number")]
        public string mandate_reference_number { get; set; }
    }
}
