//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// An installment option and associated cost.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class InstallmentOption : PayPalSerializableObject
    {
        /// <summary>
        /// Number of installments
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "term")]
        public int term { get; set; }

        /// <summary>
        /// Monthly payment
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "monthly_payment")]
        public Currency monthly_payment { get; set; }

        /// <summary>
        /// Discount amount applied to the payment, if any
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "discount_amount")]
        public Currency discount_amount { get; set; }

        /// <summary>
        /// Discount percentage applied to the payment, if any
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "discount_percentage")]
        public string discount_percentage { get; set; }
    }
}
