//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// Transaction resources related to a parent payment.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class RelatedResources : PayPalSerializableObject
    {
        /// <summary>
        /// Sale transaction
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "sale")]
        public Sale sale { get; set; }

        /// <summary>
        /// Authorization transaction
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "authorization")]
        public Authorization authorization { get; set; }

        /// <summary>
        /// Order transaction
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "order")]
        public Order order { get; set; }

        /// <summary>
        /// Capture transaction
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "capture")]
        public Capture capture { get; set; }

        /// <summary>
        /// Refund transaction
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "refund")]
        public Refund refund { get; set; }
    }
}
