//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using System.Collections.Generic;
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// A list of webhook event resources returned from a search operation.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class WebhookEventList : PayPalRelationalObject
    {
        /// <summary>
        /// A list of Webhooks event resources
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "events")]
        public List<WebhookEvent> events { get; set; }

        /// <summary>
        /// Number of items returned in each range of results. Note that the last results range could have fewer items than the requested number of items.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "count")]
        public int count { get; set; }
    }
}
